export const DEMO_SONGS: Array<{ title: string; artist: string }> = [
  { title: "Firm Foundation", artist: "Cody Carnes" },
  { title: "Tremble", artist: "Mosaic MSC" },
  { title: "Goodness of God", artist: "Bethel Music" },
  { title: "Build My Life", artist: "Housefires" },
  { title: "Great Are You Lord", artist: "All Sons and Daughters" },
  { title: "Worthy Is The Name", artist: "Elevation Worship" },
  { title: "Oceans (Where Feet May Fail)", artist: "Hillsong UNITED" },
  { title: "What a Beautiful Name", artist: "Hillsong Worship" },
  { title: "Way Maker", artist: "Sinach" },
  { title: "How Great Is Our God", artist: "Chris Tomlin" },
  { title: "How He Loves", artist: "John Mark McMillan" },
  { title: "Amazing Grace (My Chains Are Gone)", artist: "Chris Tomlin" },
  { title: "10,000 Reasons (Bless the Lord)", artist: "Matt Redman" },
  { title: "Cornerstone", artist: "Hillsong Worship" },
  { title: "King of Kings", artist: "Hillsong Worship" },
  { title: "Living Hope", artist: "Phil Wickham" },
  { title: "Reckless Love", artist: "Cory Asbury" },
  { title: "Graves Into Gardens", artist: "Elevation Worship" },
  { title: "Battle Belongs", artist: "Phil Wickham" },
  { title: "Blessed Be Your Name", artist: "Matt Redman" },
  { title: "Forever", artist: "Kari Jobe" },
  { title: "Holy Spirit", artist: "Bryan & Katie Torwalt" },
  { title: "Good Good Father", artist: "Chris Tomlin" },
  { title: "Same God", artist: "Elevation Worship" },
  { title: "The Way", artist: "Pat Barrett" },
  { title: "No Longer Slaves", artist: "Bethel Music" },
  { title: "Spirit Break Out", artist: "Kim Walker-Smith" },
  { title: "Christ Is Enough", artist: "Hillsong Worship" },
  { title: "Is He Worthy", artist: "Andrew Peterson" },
  { title: "O Come to the Altar", artist: "Elevation Worship" },
  { title: "Lion and the Lamb", artist: "Bethel Music" },
  { title: "Do It Again", artist: "Elevation Worship" },
  { title: "Who You Say I Am", artist: "Hillsong Worship" },
  { title: "New Wine", artist: "Hillsong Worship" },
  { title: "This Is Amazing Grace", artist: "Phil Wickham" },
  { title: "Here Again", artist: "Elevation Worship" },
  { title: "So Will I (100 Billion X)", artist: "Hillsong UNITED" },
  { title: "Raise a Hallelujah", artist: "Bethel Music" },
  { title: "Yes I Will", artist: "Vertical Worship" },
  { title: "God of Revival", artist: "Bethel Music" },
  { title: "Lord I Need You", artist: "Matt Maher" },
  { title: "Nothing Else", artist: "Cody Carnes" },

  // A larger title catalog for demo search/typeahead (metadata only).
  { title: "Bless the Lord (Psalm 103)", artist: "Worship Together" },
  { title: "Shout to the Lord", artist: "Darlene Zschech" },
  { title: "In Christ Alone", artist: "Keith Getty & Stuart Townend" },
  { title: "Be Thou My Vision", artist: "Traditional" },
  { title: "It Is Well", artist: "Traditional" },
  { title: "Great Is Thy Faithfulness", artist: "Traditional" },
  { title: "Holy, Holy, Holy", artist: "Traditional" },
  { title: "Come Thou Fount", artist: "Traditional" },
  { title: "Blessed Assurance", artist: "Traditional" },
  { title: "How Great Thou Art", artist: "Traditional" },
  { title: "The Goodness of God", artist: "Bethel Music" },
  { title: "The Blessing", artist: "Elevation Worship" },
  { title: "Jireh", artist: "Elevation Worship" },
  { title: "RATTLE!", artist: "Elevation Worship" },
  { title: "Trust In God", artist: "Elevation Worship" },
  { title: "Praise", artist: "Elevation Worship" },
  { title: "Same God", artist: "Elevation Worship" },
  { title: "See A Victory", artist: "Elevation Worship" },
  { title: "Never Lost", artist: "Elevation Worship" },
  { title: "Wait On You", artist: "Elevation Worship" },
  { title: "The Father’s House", artist: "Cory Asbury" },
  { title: "Refiner", artist: "Maverick City Music" },
  { title: "Jireh", artist: "Maverick City Music" },
  { title: "Promises", artist: "Maverick City Music" },
  { title: "I Thank God", artist: "Maverick City Music" },
  { title: "Million Little Miracles", artist: "Elevation Worship" },
  { title: "Talking To Jesus", artist: "Elevation Worship" },
  { title: "Glorious Day", artist: "Passion" },
  { title: "Build Your Church", artist: "Maverick City Music" },
  { title: "Kingdom", artist: "Maverick City Music" },
  { title: "Make Room", artist: "Community Music" },
  { title: "Spirit Lead Me", artist: "Influence Music" },
  { title: "Egypt", artist: "Bethel Music" },
  { title: "Goodness of God", artist: "Jenn Johnson" },
  { title: "The Story I’ll Tell", artist: "Maverick City Music" },
  { title: "Man of Your Word", artist: "Maverick City Music" },
  { title: "I Will Exalt You", artist: "Bethel Music" },
  { title: "Open The Eyes Of My Heart", artist: "Paul Baloche" },
  { title: "Your Grace Is Enough", artist: "Matt Maher" },
  { title: "How Great Is Our God", artist: "Chris Tomlin" },
  { title: "Our God", artist: "Chris Tomlin" },
  { title: "Whom Shall I Fear (God of Angel Armies)", artist: "Chris Tomlin" },
  { title: "Indescribable", artist: "Chris Tomlin" },
  { title: "At The Cross (Love Ran Red)", artist: "Chris Tomlin" },
  { title: "Forever Reign", artist: "Hillsong Worship" },
  { title: "Mighty To Save", artist: "Hillsong Worship" },
  { title: "Hosanna", artist: "Hillsong UNITED" },
  { title: "From The Inside Out", artist: "Hillsong UNITED" },
  { title: "With Everything", artist: "Hillsong UNITED" },
  { title: "Scandal of Grace", artist: "Hillsong Worship" },
  { title: "Broken Vessels (Amazing Grace)", artist: "Hillsong Worship" },
  { title: "Heart of Worship", artist: "Matt Redman" },
  { title: "Blessed Be Your Name", artist: "Matt Redman" },
  { title: "You Never Let Go", artist: "Matt Redman" },
  { title: "The Praise Is Yours", artist: "Bethel Music" },
  { title: "This Is The Air I Breathe", artist: "Michael W. Smith" },
  { title: "Agnus Dei", artist: "Michael W. Smith" },
  { title: "Here I Am To Worship", artist: "Tim Hughes" },
  { title: "Happy Day", artist: "Tim Hughes" },
  { title: "I Could Sing of Your Love Forever", artist: "Delirious?" },
  { title: "Majesty", artist: "Delirious?" },
  { title: "Did You Feel The Mountains Tremble?", artist: "Delirious?" },
  { title: "I Am Free", artist: "Newsboys" },
  { title: "God’s Not Dead", artist: "Newsboys" },
  { title: "Jesus Paid It All", artist: "Kristian Stanfill" },
  { title: "One Thing Remains", artist: "Jesus Culture" },
  { title: "Set A Fire", artist: "Jesus Culture" },
  { title: "Break Every Chain", artist: "Jesus Culture" },
  { title: "Fierce", artist: "Jesus Culture" },
  { title: "Rooftops", artist: "Jesus Culture" },
  { title: "This Is A Move", artist: "Brandon Lake" },
  { title: "Gratitude", artist: "Brandon Lake" },
  { title: "Too Good To Not Believe", artist: "Brandon Lake" },
  { title: "I Need A Ghost", artist: "Brandon Lake" },
  { title: "Praise You Anywhere", artist: "Brandon Lake" },
  { title: "I Believe", artist: "Phil Wickham" },
  { title: "House of the Lord", artist: "Phil Wickham" },
  { title: "This Is Our God", artist: "Phil Wickham" },
  { title: "Great Things", artist: "Phil Wickham" },
  { title: "Living Hope", artist: "Phil Wickham" },
  { title: "Battle Belongs", artist: "Phil Wickham" },
  { title: "The Jesus Way", artist: "Phil Wickham" },
  { title: "God of Wonders", artist: "Third Day" },
  { title: "Cry Out To Jesus", artist: "Third Day" },
  { title: "I Need You", artist: "Third Day" },
  { title: "Revelation Song", artist: "Kari Jobe" },
  { title: "Forever", artist: "Kari Jobe" },
  { title: "The Presence of the Lord", artist: "Kari Jobe" },
  { title: "Holy Spirit", artist: "Kari Jobe" },
  { title: "No Sweeter Name", artist: "Kari Jobe" },
  { title: "The Stand", artist: "Hillsong UNITED" },
  { title: "Revelation", artist: "Hillsong UNITED" },
  { title: "Lead Me To The Cross", artist: "Hillsong UNITED" },
  { title: "Where The Spirit of the Lord Is", artist: "Hillsong Worship" },
  { title: "So Will I (100 Billion X)", artist: "Hillsong UNITED" },
  { title: "Another In The Fire", artist: "Hillsong UNITED" },
  { title: "Good Grace", artist: "Hillsong UNITED" },
  { title: "Not Today", artist: "Hillsong UNITED" },
  { title: "Fresh Wind", artist: "Hillsong Worship" },
  { title: "Touch of Heaven", artist: "Hillsong Worship" },
  { title: "Pursue / All I Need Is You", artist: "Hillsong UNITED" },
  { title: "King of My Heart", artist: "Bethel Music" },
  { title: "No Longer Slaves", artist: "Bethel Music" },
  { title: "Stand In Your Love", artist: "Bethel Music" },
  { title: "Living Hope", artist: "Bethel Music" },
  { title: "Raise a Hallelujah", artist: "Bethel Music" },
  { title: "Endless Alleluia", artist: "Bethel Music" },
  { title: "God of Revival", artist: "Bethel Music" },
  { title: "Champion", artist: "Bethel Music" },
  { title: "The Lion and the Lamb", artist: "Bethel Music" },
  { title: "Goodness of God", artist: "Bethel Music" },
  { title: "God I Look To You", artist: "Bethel Music" },
  { title: "Ever Be", artist: "Bethel Music" },
  { title: "Great Are You Lord", artist: "All Sons and Daughters" },
  { title: "All The Poor And Powerless", artist: "All Sons and Daughters" },
  { title: "Great Are You Lord", artist: "One Sonic Society" },
  { title: "Amazing Grace", artist: "Traditional" },
  { title: "Nothing But The Blood", artist: "Traditional" },
  { title: "The Stand", artist: "Hillsong" },
  { title: "One Name", artist: "Naomi Raine" },
  { title: "Jehovah Jireh", artist: "Elevation Worship" },
  { title: "Believe For It", artist: "CeCe Winans" },
  { title: "The Goodness", artist: "TobyMac" },
  { title: "Great I Am", artist: "New Life Worship" },
  { title: "Overcome", artist: "Jon Egan" },
  { title: "Your Love Never Fails", artist: "Jesus Culture" },
  { title: "Forever (We Sing Hallelujah)", artist: "Bethel Music" },
  { title: "Jesus We Love You", artist: "Bethel Music" },
  { title: "One Thing Remains", artist: "Bethel Music" },
  { title: "The Anchor", artist: "Bethel Music" },
  { title: "Beautiful Name", artist: "Hillsong Worship" },
  { title: "Healer", artist: "Hillsong" },
  { title: "Mighty to Save", artist: "Hillsong" },
  { title: "O Praise The Name (Anástasis)", artist: "Hillsong Worship" },
  { title: "King of Kings", artist: "Hillsong Worship" },
  { title: "Awake My Soul", artist: "Hillsong Worship" },
  { title: "What A Friend", artist: "Hillsong Worship" },
  { title: "Touch The Sky", artist: "Hillsong UNITED" },
  { title: "All I Need Is You", artist: "Hillsong UNITED" },
  { title: "I Surrender", artist: "Hillsong Worship" },
  { title: "Cornerstone", artist: "Hillsong Worship" },
  { title: "The Lord’s Prayer", artist: "Hillsong Worship" },
  { title: "Good Good Father", artist: "Housefires" },
  { title: "Yes and Amen", artist: "Housefires" },
  { title: "Good Good Father", artist: "Pat Barrett" },
  { title: "The Way (New Horizon)", artist: "Pat Barrett" },
  { title: "Canvas and Clay", artist: "Pat Barrett" },
  { title: "Better", artist: "Pat Barrett" },
  { title: "As You Find Me", artist: "Hillsong Worship" },
  { title: "King of My Heart", artist: "John Mark McMillan" },
  { title: "How He Loves", artist: "Crowder" },
  { title: "All My Hope", artist: "Crowder" },
  { title: "Run Devil Run", artist: "Crowder" },
  { title: "Come As You Are", artist: "Crowder" },
  { title: "All My Hope", artist: "Crowder" },
  { title: "I Know A Ghost", artist: "Crowder" },
  { title: "Evidence", artist: "Josh Baldwin" },
  { title: "Stand In Your Love", artist: "Josh Baldwin" },
  { title: "Made For More", artist: "Josh Baldwin" },
  { title: "My King Forever", artist: "Josh Baldwin" },
  { title: "Famous For (I Believe)", artist: "Tauren Wells" },
  { title: "Known", artist: "Tauren Wells" },
  { title: "Hills and Valleys", artist: "Tauren Wells" },
  { title: "King of My Heart", artist: "Bethel Music" },
  { title: "The Heart of Worship", artist: "Matt Redman" },
  { title: "Son of Suffering", artist: "Bethel Music" },
  { title: "Do It Again", artist: "Bethel Music" },
  { title: "Resurrecting", artist: "Elevation Worship" },
  { title: "There Is A Cloud", artist: "Elevation Worship" },
  { title: "My Testimony", artist: "Elevation Worship" },
  { title: "Echo", artist: "Elevation Worship" },
  { title: "The King Is Among Us", artist: "Elevation Worship" },
  { title: "The Moon Is a Loyal Companion", artist: "Unknown" },
];
